function hdr = pat_create_vol(fname, dim, dt, pinfo, mat, n, data)
hdr = struct('fname',fname,...
    'dim', dim,...
    'dt',   dt,...
    'pinfo',pinfo,...
    'mat',  mat,...
    'n', n);
hdr = spm_create_vol(hdr);
spm_write_vol(hdr, data);
end